#ifndef SHAREDSTRUCTURES_H
#define SHAREDSTRUCTURES_H

#define DEFAULT_SERVER_LISTEN_PORT		50513

// 64KB Chunk Size
#define FILE_CHUNK_SIZE			64*1024

#define SHA1_BYTECOUNT			20


#define CONN_CONTROL_REQUEST_FILE_LIST				0x002
#define CONN_CONTROL_LIST_REQUEST_GRANTED			0x003
#define CONN_CONTROL_LIST_REQUEST_REJECTED			0x004

#define CONN_CONTROL_REQUEST_FILE_DOWNLOAD			0x008
#define CONN_CONTROL_FILE_REQUEST_GRANTED			0x009
#define CONN_CONTROL_FILE_REQUEST_REJECTED			0x010

#define CONN_CONTROL_REQUEST_PARTIAL_FILE_DOWNLOAD	0x016
#define CONN_CONTROL_FILE_COMPLETE			0x128

enum ConnectionControl { REQUEST_FILE_LIST,
						 LIST_REQUEST_GRANTED,
						 LIST_REQUEST_REJECTED,
						 LIST_REQUEST_EMPTY,

						 REQUEST_FILE_DOWNLOAD,
						 FILE_DOWNLOAD_REQUEST_GRANTED,
						 FILE_DOWNLOAD_REQUEST_REJECTED,

						 REQUEST_PARTIAL_FILE,
						 PARTIAL_FILE_REQUEST_GRANTED,
						 PARTIAL_FILE_REQUEST_REJECTED,

						 FILE_COMPLETED };

struct connControlMsg
{
	ConnectionControl message;
	char sha1_id[20];
};

struct file
{
	struct
	{
		unsigned int name_len;
		unsigned int file_size;
		unsigned int file_id;
	} basic_info;

	char *file_name;
};

#endif
